server:
  servlet:
    context-path:
      /sell

spring:
# 数据库配置
  datasource:
    username: root
    password: xyxy
    url: jdbc:mysql://localhost:3306/sell_new?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379

# 日志格式
logging:
  pattern:
    console: "%d -%msg%n"

wechat:
  mpAppId: wxac678757f8fa0868
  mpAppSecret: 82a44ae9aeaaca6647dc6cae4148d612

project-url:
  wechatMpAuthorize:  http://lwwechatsell.s1.natapp.cc